_wandb:
    value:
        cli_version: 0.23.1
        e:
            p7ghszx62xo0z9ip1tlua7nsjfc02ogk:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 32
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "4294967296"
                args:
                    - uncertainty.beta_strategy=constant
                    - uncertainty.beta_start=0.0
                    - uncertainty.beta_end=0.0
                    - hydra.run.dir=outputs/beta_0.0
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "677194092544"
                email: 12guocheng@gmail.com
                executable: /Users/wuguocheng/workshop/dynamic_nll/.venv/bin/python
                git:
                    commit: 4282cdc39db1063798eb4a267c777cbf4e755a1b
                    remote: https://github.com/GuoCheng12/dynamic_nll.git
                host: wuguochengdeMacBook-Pro-2.local
                memory:
                    total: "34359738368"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/wuguocheng/workshop/dynamic_nll/train.py
                python: CPython 3.9.20
                root: /Users/wuguocheng/workshop/dynamic_nll
                startedAt: "2025-12-09T00:50:43.136838Z"
                writerId: p7ghszx62xo0z9ip1tlua7nsjfc02ogk
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 2
                - 16
                - 61
            "4": 3.9.20
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
dataset:
    value:
        name: uci_energy
        normalize: true
        path: data/uci/energy.csv
        split:
            test: 0.1
            train: 0.8
            val: 0.1
        target_column: energy
hyperparameters:
    value:
        batch_size: 128
        epochs: 100
        lr: 0.001
logging:
    value:
        project_name: beta-nll-research
        run_name: constant_0.0_to_0.0
        use_wandb: true
model:
    value:
        activation: relu
        dropout: 0
        hidden_sizes:
            - 256
            - 256
        input_dim: 1
        name: mlp
seed:
    value: 42
uncertainty:
    value:
        beta_end: 0
        beta_start: 0
        beta_strategy: constant
        loss_type: beta_nll
        total_steps: 100000
