name: nyu_depth
train_data_path: /datasets/data/sync
train_gt_path: /datasets/data/sync
eval_data_path: /datasets/data/NYU_test/test
eval_gt_path: /datasets/data/NYU_test/test
filenames_file: configs/dataset/nyudepthv2_train_files_with_gt.txt
filenames_file_eval: configs/dataset/nyudepthv2_test_files_with_gt.txt
input_height: 416
input_width: 544
min_depth: 0.001
max_depth: 10.0
min_depth_eval: 0.001
max_depth_eval: 10.0
do_random_rotate: true
degree: 2.5
eigen_crop: true
batch_size: 16
eval_batch_size: 2
num_workers: 4
use_dummy_data: false
n_samples: 100
