name: nyu_depth
data_path: /path/to/nyu/rgb
gt_path: /path/to/nyu/depth
filenames_file: /path/to/nyu/train_files.txt
input_height: 256
input_width: 256
batch_size: 16
use_dummy_data: false
n_samples: 100
