defaults:
  - _self_
  - model: depth_unet 

dataset:
  name: "nyu_depth"
  train_data_path: "/datasets/workspace/dataset/nyu_depth_v2/sync"
  train_gt_path: "/datasets/workspace/dataset/nyu_depth_v2/sync"
  filenames_file: "/datasets/workspace/dynamic_nll/configs/dataset/nyudepthv2_train_files_with_gt.txt"
  eval_data_path: "/datasets/workspace/dataset/nyu_depth_v2/official_splits"
  eval_gt_path: "/datasets/workspace/dataset/nyu_depth_v2/official_splits"
  filenames_file_eval: "/datasets/workspace/dynamic_nll/configs/dataset/nyudepthv2_test_files_with_gt.txt"
  
  input_height: 416
  input_width: 544
  min_depth: 0.001
  max_depth: 10.0
  min_depth_eval: 0.001
  max_depth_eval: 10.0
  eigen_crop: True  # 对应 --eigen_crop

  do_random_rotate: True # 对应 --do_random_rotate
  degree: 2.5            # 对应 --degree 2.5
  
  batch_size: 16         # [Modified] 从 3 改为 16
  num_workers: 16

model:
  name: "depth_unet"
  encoder: "tf_efficientnet_b5_ap"
  pretrained: True
  min_depth: 0.001
  max_val: 10.0

hyperparameters:
  lr: 1e-3           
  eval_batch_size: 1
  weight_decay: 0.1      
  epochs: 50             
  checkpoint_interval: 5 
  
uncertainty:
  beta_strategy: "constant" 
  beta_start: 1.0
  beta_end: 1.0
  total_steps: 1000      

logging:
  use_wandb: True
  project_name: "nyu_depth_ddp"
  run_name: "NYU_unet_nll_beta1.0_bs16" 
seed: 42
device: auto
